apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dummy-exporter-base

namespace: smart-home

labels:
  - pairs:
      app.kubernetes.io/name: dummy-exporter
      app.kubernetes.io/part-of: smart-home-monitoring

resources:
  - deployment.yaml
  - service.yaml
  - configmap-initial-devices.yaml

images:
  - name: dummy-exporter
    newTag: latest
