apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-data
  labels:
    app: victoriametrics
    component: metrics-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
