apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  labels:
    app: victoriametrics
    component: metrics-storage
spec:
  selector:
    app: victoriametrics
    component: metrics-storage
  ports:
    - name: http
      port: 8428
      targetPort: http
      protocol: TCP
  type: ClusterIP
