apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vmagent

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: vmagent
      app.kubernetes.io/component: collector
      app.kubernetes.io/part-of: smart-home-monitoring

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  project.kubernetes.io/component: vmagent

images:
  - name: victoriametrics/vmagent
    newTag: v1.97.1
