apiVersion: v1
kind: Service
metadata:
  name: openobserve
  labels:
    app: openobserve
    component: observability
spec:
  type: ClusterIP
  selector:
    app: openobserve
    component: observability
  ports:
    - name: http
      port: 5080
      targetPort: 5080
      protocol: TCP
    - name: grpc
      port: 5081
      targetPort: 5081
      protocol: TCP
