apiVersion: v1
kind: Service
metadata:
  name: dummy-exporter
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "smart-home-dummy-exporter-stg"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
