apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-scrape-config
data:
  scrape.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'dummy-exporter'
        static_configs:
          - targets:
            - 'stg-dummy-exporter.smart-home-staging.svc.cluster.local:9100'
        scrape_interval: 15s
        scrape_timeout: 5s
        metrics_path: '/metrics'
        honor_timestamps: true

      - job_name: 'victoria-metrics'
        static_configs:
          - targets:
            - 'localhost:8428'
        scrape_interval: 30s
        metrics_path: '/metrics'
